version: 2.1

# Import the team's config as an orb
orbs:
  team-config: << pipeline.parameters.config-override-url >>
  snyk: snyk/snyk@2.3.0

# Define parameters for configuration
parameters:
  config-override-url:
    type: string
    default: "https://raw.githubusercontent.com/<< pipeline.git.repo_owner >>/<< pipeline.git.repo_name >>/<< pipeline.git.revision >>/.circleci/team-config.yml"


workflows:
  version: 2
  main:
    jobs:
      - build:
          name: "Build Application"
          override-with: team-config/build
          context: share-docker-publishing
      - security-scan:
          name: "Security Scan"
      - test:
          name: "Test Application"
          override-with: team-config/test
          requires:
            - "Build Application"
      - deploy:
          name: "Deploy Application"
          override-with: team-config/deploy
          requires:
            - "Test Application"
            - "Security Scan"

jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run: echo "Building the application..."

  test:
    docker:
      - image: cimg/base:stable
    steps:
      - run: echo "Running tests..."

  security-scan:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            if [ -f requirements.txt ]; then
              pip install -r requirements.txt
            elif [ -f Pipfile ]; then
              pip install pipenv && pipenv install --dev
            elif [ -f pyproject.toml ]; then
              pip install -e .
            fi
      - snyk/scan:
          fail-on-issues: false
          monitor-on-build: false
          severity-threshold: high
          additional-arguments: "--all-projects"

  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - run: echo "Deploying the application..."

# Customize the steps or images as needed for your stack.
# You can override these jobs in your own repo if required. 