version: 2.1

# Import the team's config as an orb
orbs:
  team-config: << pipeline.parameters.config-override-url >>

# Define parameters for configuration
parameters:
  config-override-url:
    type: string
    default: "https://raw.githubusercontent.com/<< pipeline.git.repo_owner >>/<< pipeline.git.repo_name >>/<< pipeline.git.revision >>/.circleci/team-config.yml"


workflows:
  version: 2
  main:
    jobs:
      - build:
          name: "Build Application"
          override-with: team-config/build
          context: share-docker-publishing
      - test:
          name: "Test Application"
          override-with: team-config/test
          requires:
            - "Build Application"
      - deploy:
          name: "Deploy Application"
          override-with: team-config/deploy
          requires:
            - "Test Application"

jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run: echo "Building the application..."

  test:
    docker:
      - image: cimg/base:stable
    steps:
      - run: echo "Running tests..."

  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - run: echo "Deploying the application..."

# Customize the steps or images as needed for your stack.
# You can override these jobs in your own repo if required. 