version: 2.1

# Define the orbs we'll use
orbs:
  terraform: circleci/terraform@3.6
  aws-cli: circleci/aws-cli@5.4.0
  platform-team: https://raw.githubusercontent.com/CircleCI-Labs/platform-team-configs/883ecfa5b0d11624387665afad8d0d37e4d1eaac/orbs/platform-team.yml

jobs:
  configure-cci:
    docker:
      - image: cimg/deploy:2025.01.1
    environment:
      WEBHOOK_BODY: << pipeline.trigger_parameters.webhook.body >>
    steps:
      - checkout
      - platform-team/parse-webhook-payload
      - platform-team/build-terraform-provider-circleci:
          provider_version: "0.0.1"
      - platform-team/setup-tf-vars
      - aws-cli/setup:
          role_arn: "arn:aws:iam::${AWS_ACCOUNT_ID}:role/${AWS_IAM_PREFIX}-role"
          role_session_name: "fe-provider-demo-<< pipeline.number >>"
      - run:
          name: Generate backend config
          command: |
            echo "key=\"fe-platform-demo/port/${TARGET_REPO}.tfstate\"" > terraform/pipeline-terraform/backend.conf
      - terraform/apply:
          backend_config_file: backend.conf
          path: terraform/pipeline-terraform
          var_file: app.tfvars
      - run:
          name: Trigger initial CI/CD pipeline with empty commit
          command: |
            # Clone only the latest commit to minimize data transfer
            git clone --depth=1 https://github.com/${GITHUB_ORG}/${TARGET_REPO}.git /tmp/trigger-repo
            cd /tmp/trigger-repo
            
            # Configure git for the commit
            git config user.name "Platform Team Bot"
            git config user.email "platform-team@circleci.com"
            
            # Create and push empty commit to trigger CI/CD
            git commit --allow-empty -m "chore: trigger initial CI/CD pipeline

            This empty commit was created automatically by the platform team
            to trigger the initial CI/CD pipeline for this repository."
            git push origin main

workflows:
  provision-infrastructure:
    when:
      and:
        - equal: [ webhook, << pipeline.trigger_source >> ]
        - << pipeline.trigger_parameters.webhook.body >>
    jobs:
      - configure-cci:
          context: 
            - centralized-assest-github-envs