version: 2.1

# Define the orbs we'll use
orbs:
  terraform: circleci/terraform@3.6
  aws-cli: circleci/aws-cli@5.4.0
  gh: circleci/github-cli@2.2
  platform-team: https://raw.githubusercontent.com/CircleCI-Labs/platform-team-configs/refs/heads/main/orbs/platform-team.yml

parameters:
  template_repo:
    type: enum
    description: "Template repository to use as base"
    default: "python-starter-template"
    enum: ["python-starter-template", "node-starter-template"]
  target_repo:
    type: string
    description: "Target repository where infrastructure will be provisioned"
    default: ""


jobs:
  configure-cci:
    docker:
      - image: cimg/deploy:2025.01.1
    environment:
      WEBHOOK_BODY: << pipeline.trigger_parameters.webhook.body >>
    steps:
      - checkout
      - when:
          condition:
            equal: [ webhook, << pipeline.trigger_source >> ]
          steps:
            - platform-team/parse-webhook-payload
      - when:
          condition:
            equal: [ api, << pipeline.trigger_source >> ]
          steps:
            - platform-team/parse-ui-parameters:
                template_repo: << pipeline.parameters.template_repo >>
                target_repo: << pipeline.parameters.target_repo >>
      - platform-team/build-terraform-provider-circleci:
          provider_version: "0.2.0"
          commit_sha: "c25112d15d335388a2d980b70a8c3554e7f108d3"
      - platform-team/setup-tf-vars
      - aws-cli/setup:
          role_arn: "arn:aws:iam::${AWS_ACCOUNT_ID}:role/${AWS_IAM_PREFIX}-role"
          role_session_name: "fe-provider-demo-<< pipeline.number >>"
      - run:
          name: Generate backend config
          command: |
            echo "key=\"fe-platform-demo/port/${TARGET_REPO}.tfstate\"" > terraform/pipeline-terraform/backend.conf
      - terraform/apply:
          backend_config_file: backend.conf
          path: terraform/pipeline-terraform
          var_file: app.tfvars
      - gh/setup
      - run:
          name: Trigger initial CI/CD pipeline with empty commit
          command: |
            # Use GitHub CLI to clone (handles auth automatically) and create empty commit
            gh repo clone ${GITHUB_ORG}/${TARGET_REPO} /tmp/trigger-repo -- --depth=1
            cd /tmp/trigger-repo
            
            # Configure git for the commit
            git config user.name "Platform Team Bot"
            git config user.email "platform-team@circleci.com"
            
            # Create and push empty commit to trigger CI/CD
            git commit --allow-empty -m "chore: trigger initial CI/CD pipeline

            This empty commit was created automatically by the platform team
            to trigger the initial CI/CD pipeline for this repository."
            
            # Push using GitHub CLI (handles auth)
            git push origin main

workflows:
  provision-infrastructure:
    when:
      or:
        - and:
            - equal: [ webhook, << pipeline.trigger_source >> ]
            - << pipeline.trigger_parameters.webhook.body >>
        - and:
            - equal: [ api, << pipeline.trigger_source >> ]
            - << pipeline.parameters.template_repo >>
            - not:
                equal: [ "", << pipeline.parameters.target_repo >> ]
    jobs:
      - configure-cci:
          context: 
            - centralized-asset-github-envs