# Test for team-config orb requirement policy
test_team_config_orb_policy:
  # Test with valid configuration that includes team-config orb
  input:
    version: 2.1
    jobs:
      build:
        docker:
          - image: cimg/base:stable
  decision: &root_decision
    status: PASS
  
  cases:
    # Test with valid team-config orb (correct URL format)
    valid_team_config:
      input:
        orbs:
          team-config: "https://raw.githubusercontent.com/my-org/my-repo/main/.circleci/team-config.yml"
          docker: circleci/docker@2.8.2
      decision:
        <<: *root_decision
        status: PASS
    # Test with missing team-config orb (policy disabled)
    missing_team_config_orb:
      input:
        version: 2.1
        orbs:
          docker: circleci/docker@2.8.2
          python: circleci/python@3.1.0
        jobs:
          build:
            docker:
              - image: cimg/base:stable
      decision:
        status: PASS  # Policy is disabled
    
    # Test with no orbs section at all (policy disabled)
    no_orbs_section:
      input:
        version: 2.1
        jobs:
          build:
            docker:
              - image: cimg/base:stable
      decision:
        status: PASS  # Policy is disabled
    
    # Test with team-config orb only
    team_config_only:
      input:
        orbs:
          team-config: "https://raw.githubusercontent.com/my-org/my-repo/main/.circleci/team-config.yml"
      decision:
        <<: *root_decision
        status: PASS
    
    # Test with team-config and multiple other orbs
    team_config_with_others:
      input:
        orbs:
          team-config: "https://raw.githubusercontent.com/my-org/my-repo/main/.circleci/team-config.yml"
          docker: circleci/docker@2.8.2
          python: circleci/python@3.1.0
          node: circleci/node@5.0.0
      decision:
        <<: *root_decision
        status: PASS
    
    # Test with empty orbs section (policy disabled)
    empty_orbs_section:
      input:
        version: 2.1
        orbs: {}
        jobs:
          build:
            docker:
              - image: cimg/base:stable
      decision:
        status: PASS  # Policy is disabled
    
    # Test with team-config orb but wrong URL format (policy disabled)
    invalid_team_config_url:
      input:
        version: 2.1
        orbs:
          team-config: "https://example.com/wrong-path/config.yml"
          docker: circleci/docker@2.8.2
        jobs:
          build:
            docker:
              - image: cimg/base:stable
      decision:
        status: PASS  # Policy is disabled
    
    # Test with team-config orb with wrong filename (policy disabled)
    wrong_filename:
      input:
        version: 2.1
        orbs:
          team-config: "https://raw.githubusercontent.com/my-org/my-repo/main/.circleci/config.yml"
          docker: circleci/docker@2.8.2
        jobs:
          build:
            docker:
              - image: cimg/base:stable
      decision:
        status: PASS  # Policy is disabled
    
    # Test excluded project without team-config orb - should pass
    excluded_project_no_orb:
      input:
        meta:
          project_id: "e3914273-2713-4f0f-999d-f9fbd6748cf8"
        version: 2.1
        orbs:
          docker: circleci/docker@2.8.2
        jobs:
          build:
            docker:
              - image: cimg/base:stable
      decision:
        status: PASS  # Policy is disabled 